NXDRIVE-2442: Implement mutual TLS authentication
nuxeo/nuxeo-drive pull request #2449
Opened 2021-02-05 10:20 UTC by rom1win

2021-02-05 10:27 UTC, BoboTiG commented on nxdrive/options.py
> +    if not Path(cert_path).exists():
```suggestion
    if not Path(cert_path).is_file():
```

2021-02-05 10:27 UTC, BoboTiG commented on nxdrive/options.py
> +            f"Path to client side SSL certification file must be correct,  Invalid path: {cert_path}"
```suggestion
            f"The file {cert_path!r} does not exist"
```

2021-02-05 12:08 UTC, BoboTiG requested changes

2021-02-05 12:08 UTC, BoboTiG commented on nxdrive/utils.py
> +def client_certificate():
Types + docstring.

2021-02-05 12:08 UTC, BoboTiG commented on docs/configuration.md
> +cert_key_file = C:\certificates\client-ssl.key
The real documentation is missing, see how other options are explained in that file.

2021-02-05 12:08 UTC, BoboTiG commented on docs/changes/5.0.0.md
> +- [NXDRIVE-2442](https://jira.nuxeo.com/browse/NXDRIVE-2442): Implement mutual TLS authentication
Missing new options and functions.

2021-02-05 14:04 UTC, BoboTiG commented on docs/configuration.md
> +File that is the key to the specified [cert-file].
Missing link to cert-file?

2021-02-05 14:07 UTC, BoboTiG commented on nxdrive/exceptions.py
> +        return "No client-side SSL certificate. Use 'cert' and 'key' to provide client side SSL certificate."
```suggestion
        return "No client-side SSL certificate. Use 'cert_file' and 'cert_key_file'."
```

2021-02-05 14:08 UTC, BoboTiG commented on nxdrive/utils.py
> +            raise InvalidSSLCertificate()
It should be 
```suggestion
            raise MissingClientSSLCertificate()
```
right?

2021-02-05 14:45 UTC, manonlumeau approved these changes

2021-02-05 14:45 UTC, manonlumeau commented on docs/configuration.md
> +If set, [cert-key-file](#cert-key-file) must also be set otherwise it will be ignored.
```suggestion
If set, [cert-key-file](#cert-key-file) must also be set, otherwise it will be ignored.
```

2021-02-05 14:45 UTC, manonlumeau commented on docs/configuration.md
> +If set, [cert-file](#cert-file) must also be set otherwise it will be ignored.
```suggestion
If set, [cert-file](#cert-file) must also be set, otherwise it will be ignored.
```

2021-02-05 16:37 UTC, BoboTiG commented on nxdrive/exceptions.py
> +        return "No client-side SSL certificate. Use 'cert_file' and 'cert_key_file'."
```suggestion
        return "No client-side SSL certificate. Use 'cert-file' and 'cert-key-file'."
```

2021-02-08 16:13 UTC, BoboTiG commented on nxdrive/exceptions.py
> +class EncryptedSSLCertificateKey(DriveError):
Missing changelog.

2021-02-08 16:13 UTC, BoboTiG commented on nxdrive/gui/api.py
> +    def _has_valid_ssl_certificate(self, server_url: str, /) -> str:
Could you rename that method to have a more explicit name? It now returns an error label. Maybe something like `_get_ssl_error()` would more suited?

2021-02-08 17:12 UTC, BoboTiG approved these changes

2021-02-15 13:13 UTC, BoboTiG commented on docs/changes/5.0.0.md
> +- Added utils.py::`client_certificate()
```suggestion
- Added utils.py::`client_certificate()
- Changed the return type of utils.py::`test_url()` from `bool` to `str`
```

2021-02-15 13:15 UTC, merged