NXDRIVE-2844: Nuxeo Drive transfer failed after removing hardware
nuxeo/nuxeo-drive pull request #4046
Opened 2023-07-27 06:00 UTC by gitofanindya

2023-07-27 11:02 UTC, mr-shekhar requested changes

2023-07-28 05:04 UTC, mr-shekhar approved these changes

2023-07-28 05:42 UTC, swetayadav1 approved these changes

2023-07-28 06:10 UTC, gitofanindya commented on docs/changes/5.3.2.md
> +- [NXDRIVE-2844](https://jira.nuxeo.com/browse/NXDRIVE-2844): Nuxeo Drive transfer failed after removing hardware
DONE

2023-07-28 06:13 UTC, gitofanindya commented on tests/functional/test_processor.py
> +def test__synchronize_direct_transfer(manager_factory):
CHANGED

2023-07-28 06:42 UTC, merged