NXDRIVE-2901: Authorization Error for OAuth
nuxeo/nuxeo-drive pull request #4616
Opened 2024-02-21 05:48 UTC by gitofanindya

2024-02-28 05:49 UTC, mr-shekhar requested changes

2024-02-28 05:49 UTC, mr-shekhar commented on nxdrive/auth/oauth2.py
> +        subclient_kwargs = kwargs.get("subclient_kwargs")
kwargs usage incorrect. Pl check

2024-02-28 10:09 UTC, gitofanindya commented on nxdrive/auth/oauth2.py
> +        subclient_kwargs = kwargs.get("subclient_kwargs")
updated. please review again.

2024-04-02 12:17 UTC, swetayadav1 approved these changes

2024-04-03 06:33 UTC, mr-shekhar approved these changes
👍

2024-04-03 06:34 UTC, poojadaine approved these changes

2024-04-03 06:43 UTC, merged